### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by CxcCoding** [thevpaliy/Material-Motion#1]
A TaskDescription's primary color should be opaque ？？

**Comment by vpaliy** [comment]
I'm not sure what do you mean by `TaskDescriotion's`. Could you provide more details on the issue? And why is it tagged as `RuntimeException`?

**Comment by CxcCoding** [comment]
Are you a google phone?

**Comment by CxcCoding** [comment]
I can not start the app, he will crash, log: Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque。

**Comment by CxcCoding** [comment]
You have Genymotion

**Comment by michaldrabik** [comment]
Color primary can't have an alpha. Change it it to 
`<color name="colorPrimary">#12517b</color>` and the app starts.

Unfortuneatly all I can see is just a blank white screen. :( Running on AS 3.0 Beta4, emulator Nexus5 API23

**EDIT Oh nevermind. There is a navigation drawer on the right side...**

**Comment by CxcCoding** [comment]
I can run now but nothing else

**Comment by CxcCoding** [comment]
I am also a blank page ah

**Comment by michaldrabik** [comment]
@Dream-cxc There is a navigation drawer on the right side. Just swipe from right edge.

**Comment by Dream-cxc** [comment]
@michaldrabik  
Do you have a screenshot of my Genymotion?  help me  ，thank you

**Comment by CxcCoding** [comment]
thank you， @michaldrabik @vpaliyX    share it

**Comment by vpaliy** [comment]
I've added a commit, it should fix this problem.

**Comment by vpaliy** [comment]
Since nobody has any complaints, I'm closing this issue.
